export const CONTACT_CREATE = 'CONTACT_CREATE';
export const CONTACT_UPDATE = 'CONCAT_UPDATE';
export const CONTACT_DELETE = 'CONTACT_DELETE';
export const CONTACT_DELETE_ALL = 'CONTACT_DELETE_ALL';
export const CONTACT_FETCH_ALL = 'CONTACT_FETCH_ALL';
